ordering:
  about-us:
    -
      our-mission: ''
      the-need: ''
      leadership-team: ''
      where-we-work: ''
    -
      our-blog: ''
      testimonials: ''
      partners: ''
      contact-us: ''
  locations: ''
  resources:
    leading-well: ''
    training: ''
    get-involved: ''
  donate: ''
items:
  about-us:
    attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: 420px
  about-us/our-mission:
    object_id: 499
  about-us/the-need:
    object_id: 511
  about-us/leadership-team:
    object_id: 27
  about-us/where-we-work:
    object_id: 61
  about-us/our-blog:
    object_id: 55
  about-us/testimonials:
    object_id: 524
  about-us/partners:
    object_id: 548
  about-us/contact-us:
    object_id: 89
  locations:
    object_id: 83
  resources:
    object_id: 1251
  resources/leading-well:
    object_id: 85
  resources/training:
    object_id: 102
  resources/get-involved:
    object_id: 537
  donate:
    object_id: 438
    attributes: {  }
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
