name: home_-_particles
timestamp: 1576274008
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1576273728
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  messages:
    system-messages-6041: 'System Messages'
  logo:
    logo-3667: 'Logo / Image'
    logo-9777: 'Logo / Image'
  menu:
    menu-8567: Menu
  social:
    social-3362: Social
  copyright:
    copyright-3777: Copyright
  horizontalmenu:
    horizontalmenu-3387: 'Horizontal Menu'
  totop:
    totop-7974: 'To Top'
  mobile-menu:
    mobile-menu-7865: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-6041: system-messages-7972
    logo-3667: logo-9608
    menu-8567: menu-6409
    social-3362: social-3171
    logo-9777: logo-9571
    copyright-3777: copyright-1736
    horizontalmenu-3387: horizontalmenu-9034
    totop-7974: totop-8670
    mobile-menu-7865: mobile-menu-5697
